// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { NavBar } from "@/components/ui/NavBar";
import { Toaster } from "sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const pathname = usePathname();
  // const isAdmin = pathname.startsWith("/admin");
  return (
    <>
     {/*/ <NavBar /> */}
      {children}
      <Toaster />
    </>
  );
}
