import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "sonner"
import { AppSidebar } from "@/components/ui/app-sidebar";

import LoginPage from "../(auth)/login/page";
import AppSidebarInset from "@/components/ui/sidebar-inset";
import { NavigationEvents } from "@/components/test";
import { Suspense } from "react";
export const metadata = {
  title: "Mohamed Saad AZIZI",
  description: "Generated by create next app",
};
const authenticated = true;

export default function RootLayout({ children }) {
  return (
    <>
      <SidebarProvider>
        <AppSidebar />
        <AppSidebarInset>{children}</AppSidebarInset>
      </SidebarProvider>
      <Toaster />
      <Suspense fallback={"loading..."}>
        <NavigationEvents />
      </Suspense>
    </>
    //     {authenticated ? <SideBar>{children}</SideBar> : <LoginPage />}
  );
}
