import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SideBar } from "@/components/ui/sideBarApp";
import LoginPage from "../login/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mohamed Saad AZIZI",
  description: "Generated by create next app",
};
const authenticated = true;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {authenticated ? <SideBar>{children}</SideBar> : <LoginPage />}
      </body>
    </html>
  );
}
