export const metadata = {
  title: "Mohamed Saad AZIZI",
  description: "Generated by create next app",
};

import RootLayout from "./root-layout";

export default function Layout({ children }) {
  return <RootLayout>{children}</RootLayout>;
}
